config/routes.rb
Rails.application.routes.draw do
  root 'virtual_cheques#index'
  resources :virtual_cheques, except: [:edit, :update, :destroy] do
    collection do
      get :filter
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/virtual_cheque.rb
# frozen_string_literal: true

require 'humanize'

class VirtualCheque < ApplicationRecord
  before_create :capitalize_names
  after_create :update_amount_in_words

  validates :recipient_name, :amount, :date, presence: true

  scope :filter_by_name, -> (rn) { where(recipient_name: rn) }

  private

  def capitalize_names
    self.recipient_name = recipient_name.titleize
  end

  def update_amount_in_words
    self.amount_in_words = translate_amount_to_words
    save
  end

  def translate_amount_to_words
    amn = format('%.2f', amount).split('.')
    amn.map.with_index do |n, i|
      dollar_words = amn[1].to_i > 0 ? ' dollars and': ' dollars'

      # checks for unnecessary zeros and removes them
      # capitalizes all words apart from 'and'
      n.sub!(/^0*/, '').to_i > 0 && (n.to_i.humanize.delete(',').titleize.gsub('And', 'and') +
        (i == 0 ? dollar_words : ' cents')) || ''
    end.join(' ').strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/virtual_cheques_controller.rb
# frozen_string_literal: true

class VirtualChequesController < ApplicationController
  def index
    @virtual_cheque = VirtualCheque.new
    @virtual_cheques = VirtualCheque.all
  end

  def new
    @virtual_cheque = VirtualCheque.new
  end

  def create
    @virtual_cheque = VirtualCheque.create(virtual_cheque_params)
  end

  def show
    @virtual_cheque = VirtualCheque.find_by(id: params[:id])
  end

  def filter
    @virtual_cheques = VirtualCheque.filter_by_name(params[:recipient_name])
  end

  private

  def virtual_cheque_params
    params.require(:virtual_cheque).permit(:recipient_name, :date, :amount, :amount_in_words)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VirtualCheckCreator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <%= link_to "Jay's VCG", root_path, class: 'brand-logo' %>
        <ul id="nav-mobile" class="right">
          <li>
            <%= link_to 'New Virtual Cheque', new_virtual_cheque_path, remote: true,
                class: 'modal-trigger', data: { target: 'modal1' } %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/virtual_cheques/_filter.html.erb
<%= render @virtual_cheques %>

app/views/virtual_cheques/_form.html.erb
<%= simple_form_for @virtual_cheque, remote: true do |f| %>
  <div class="row vcg-modal">
    <div class="col s12">
      <%= f.error :base %>
    </div>

    <div class="form-elements">
      <div class="col s12">
        <%= f.input :recipient_name %>
      </div>

      <div class="col s6">
        <%= f.input :date, as: :string, input_html: { class: 'datepicker' } %>
      </div>

      <div class="col s6">
        <%= f.input :amount, as: :decimal %>
      </div>

      <div class="modal-footer col s12">
        <div class="left">
          <a href="#" id="cancel" class="btn waves-effect waves-teal">Cancel</a>
        </div>
        <%= f.button :submit, 'Generate Virtual Cheque', remote: true,
            class: 'waves-effect waves-light', id: 'create_virtual_cheque' %>
      </div>
    </div>

    <div class="view-elements">
      <div class="col s12 view-element">
        <h5 class="title">Cheque for: <%= @virtual_cheque.recipient_name %></h5>
      </div>

      <div class="col s6" view-element>
        <h5 class="title">Dated: <%= @virtual_cheque.date %></h5>
      </div>


      <div class="col s6" view-element>
        <h5 class="title">Amount: <%= number_to_currency(@virtual_cheque.amount) %></h5>
      </div>

      <div class="col s12 view-element">
        <h5 class="title">Amount in words: <%= @virtual_cheque.amount_in_words %></h5>
      </div>

      <div class="modal-footer col s12">
        <div class="left">
          <a href="#" id="cancel" class="btn waves-effect waves-teal">Close</a>
        </div>
    </div>
    </div>
  </div>
<% end %>

app/views/virtual_cheques/_virtual_cheque.html.erb
<%= tag.tr virtual_cheque do %>
  <td><%= virtual_cheque.date %></td>
  <td>
    <%= link_to virtual_cheque.recipient_name,
      filter_virtual_cheques_path(recipient_name: virtual_cheque.recipient_name),
      remote: true %>
  </td>
  <td><%= number_to_currency(virtual_cheque.amount) %></td>
  <td><%= link_to 'View virtual cheque', virtual_cheque_path(virtual_cheque), remote: true %></td>
<% end %>

app/views/virtual_cheques/create.js.erb
<% if @virtual_cheque.errors.present? %>
  $('#modal1').html("<%= j(render 'form') %>");
<% else %>
  $('#modal1').html("<%= j(render 'form') %>");
  $('.form-elements').css('display', 'none')
  $('.view-elements').css('display', 'inline-block')
<% end %>

app/views/virtual_cheques/filter.js.erb
$('tbody').html("<%= j(render 'filter') %>")
$('#clear_filter').html("<%= j(link_to 'Clear filter', virtual_cheques_path, remote: true) %>")

app/views/virtual_cheques/index.html.erb
<div id="modal1" class="modal">
 <%= render 'form' %>
</div>

<div id="clear_filter"></div>

<% if @virtual_cheques.empty? %>
  <div class="center-align no-virtual-cheques">
    There are no virtual cheques
    <br />
    Start adding virtual cheques by clicking <%= link_to 'here',
      new_virtual_cheque_path, remote: true, class: 'modal-trigger', data: { target: 'modal1' } %>
  </div>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Recipient name</th>
        <th>Amount</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @virtual_cheques %>
    </tbody>
  </table>
<% end %>

app/views/virtual_cheques/index.js.erb
$('tbody').html("<%= j(render 'filter') %>")
$('#clear_filter').html("")

app/views/virtual_cheques/new.js.erb
$("#modal1").show();

app/views/virtual_cheques/show.js.erb
$("#modal1").show();
$('#modal1').html("<%= j(render 'form') %>");
$('.form-elements').css('display', 'none')
$('.view-elements').css('display', 'inline-block')